name: Build, Test (Playwright), and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name
  pull_request:
    branches:
      - main # Or your main branch name

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    name: Build, Test, and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npm install -D @playwright/test@latest

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Build Astro Production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Ensure your Astro build outputs to this directory
          force_orphan: true # Only needed for the first deployment to a dedicated gh-pages branch
          user_name: ${{ github.event.inputs.deploy_user_name || github.actor }}
          user_email: ${{ github.event.inputs.deploy_user_email || github.event.head_commit.author.email }}